// Code generated by ent, DO NOT EDIT.

package backup

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/netops/asset-manager/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Backup {
	return predicate.Backup(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Backup {
	return predicate.Backup(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Backup {
	return predicate.Backup(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Backup {
	return predicate.Backup(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Backup {
	return predicate.Backup(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Backup {
	return predicate.Backup(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Backup {
	return predicate.Backup(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Backup {
	return predicate.Backup(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Backup {
	return predicate.Backup(sql.FieldLTE(FieldID, id))
}

// DeviceIP applies equality check predicate on the "device_ip" field. It's identical to DeviceIPEQ.
func DeviceIP(v string) predicate.Backup {
	return predicate.Backup(sql.FieldEQ(FieldDeviceIP, v))
}

// Filename applies equality check predicate on the "filename" field. It's identical to FilenameEQ.
func Filename(v string) predicate.Backup {
	return predicate.Backup(sql.FieldEQ(FieldFilename, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Backup {
	return predicate.Backup(sql.FieldEQ(FieldContent, v))
}

// SizeBytes applies equality check predicate on the "size_bytes" field. It's identical to SizeBytesEQ.
func SizeBytes(v int64) predicate.Backup {
	return predicate.Backup(sql.FieldEQ(FieldSizeBytes, v))
}

// Vendor applies equality check predicate on the "vendor" field. It's identical to VendorEQ.
func Vendor(v string) predicate.Backup {
	return predicate.Backup(sql.FieldEQ(FieldVendor, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Backup {
	return predicate.Backup(sql.FieldEQ(FieldCreatedAt, v))
}

// DeviceIPEQ applies the EQ predicate on the "device_ip" field.
func DeviceIPEQ(v string) predicate.Backup {
	return predicate.Backup(sql.FieldEQ(FieldDeviceIP, v))
}

// DeviceIPNEQ applies the NEQ predicate on the "device_ip" field.
func DeviceIPNEQ(v string) predicate.Backup {
	return predicate.Backup(sql.FieldNEQ(FieldDeviceIP, v))
}

// DeviceIPIn applies the In predicate on the "device_ip" field.
func DeviceIPIn(vs ...string) predicate.Backup {
	return predicate.Backup(sql.FieldIn(FieldDeviceIP, vs...))
}

// DeviceIPNotIn applies the NotIn predicate on the "device_ip" field.
func DeviceIPNotIn(vs ...string) predicate.Backup {
	return predicate.Backup(sql.FieldNotIn(FieldDeviceIP, vs...))
}

// DeviceIPGT applies the GT predicate on the "device_ip" field.
func DeviceIPGT(v string) predicate.Backup {
	return predicate.Backup(sql.FieldGT(FieldDeviceIP, v))
}

// DeviceIPGTE applies the GTE predicate on the "device_ip" field.
func DeviceIPGTE(v string) predicate.Backup {
	return predicate.Backup(sql.FieldGTE(FieldDeviceIP, v))
}

// DeviceIPLT applies the LT predicate on the "device_ip" field.
func DeviceIPLT(v string) predicate.Backup {
	return predicate.Backup(sql.FieldLT(FieldDeviceIP, v))
}

// DeviceIPLTE applies the LTE predicate on the "device_ip" field.
func DeviceIPLTE(v string) predicate.Backup {
	return predicate.Backup(sql.FieldLTE(FieldDeviceIP, v))
}

// DeviceIPContains applies the Contains predicate on the "device_ip" field.
func DeviceIPContains(v string) predicate.Backup {
	return predicate.Backup(sql.FieldContains(FieldDeviceIP, v))
}

// DeviceIPHasPrefix applies the HasPrefix predicate on the "device_ip" field.
func DeviceIPHasPrefix(v string) predicate.Backup {
	return predicate.Backup(sql.FieldHasPrefix(FieldDeviceIP, v))
}

// DeviceIPHasSuffix applies the HasSuffix predicate on the "device_ip" field.
func DeviceIPHasSuffix(v string) predicate.Backup {
	return predicate.Backup(sql.FieldHasSuffix(FieldDeviceIP, v))
}

// DeviceIPEqualFold applies the EqualFold predicate on the "device_ip" field.
func DeviceIPEqualFold(v string) predicate.Backup {
	return predicate.Backup(sql.FieldEqualFold(FieldDeviceIP, v))
}

// DeviceIPContainsFold applies the ContainsFold predicate on the "device_ip" field.
func DeviceIPContainsFold(v string) predicate.Backup {
	return predicate.Backup(sql.FieldContainsFold(FieldDeviceIP, v))
}

// FilenameEQ applies the EQ predicate on the "filename" field.
func FilenameEQ(v string) predicate.Backup {
	return predicate.Backup(sql.FieldEQ(FieldFilename, v))
}

// FilenameNEQ applies the NEQ predicate on the "filename" field.
func FilenameNEQ(v string) predicate.Backup {
	return predicate.Backup(sql.FieldNEQ(FieldFilename, v))
}

// FilenameIn applies the In predicate on the "filename" field.
func FilenameIn(vs ...string) predicate.Backup {
	return predicate.Backup(sql.FieldIn(FieldFilename, vs...))
}

// FilenameNotIn applies the NotIn predicate on the "filename" field.
func FilenameNotIn(vs ...string) predicate.Backup {
	return predicate.Backup(sql.FieldNotIn(FieldFilename, vs...))
}

// FilenameGT applies the GT predicate on the "filename" field.
func FilenameGT(v string) predicate.Backup {
	return predicate.Backup(sql.FieldGT(FieldFilename, v))
}

// FilenameGTE applies the GTE predicate on the "filename" field.
func FilenameGTE(v string) predicate.Backup {
	return predicate.Backup(sql.FieldGTE(FieldFilename, v))
}

// FilenameLT applies the LT predicate on the "filename" field.
func FilenameLT(v string) predicate.Backup {
	return predicate.Backup(sql.FieldLT(FieldFilename, v))
}

// FilenameLTE applies the LTE predicate on the "filename" field.
func FilenameLTE(v string) predicate.Backup {
	return predicate.Backup(sql.FieldLTE(FieldFilename, v))
}

// FilenameContains applies the Contains predicate on the "filename" field.
func FilenameContains(v string) predicate.Backup {
	return predicate.Backup(sql.FieldContains(FieldFilename, v))
}

// FilenameHasPrefix applies the HasPrefix predicate on the "filename" field.
func FilenameHasPrefix(v string) predicate.Backup {
	return predicate.Backup(sql.FieldHasPrefix(FieldFilename, v))
}

// FilenameHasSuffix applies the HasSuffix predicate on the "filename" field.
func FilenameHasSuffix(v string) predicate.Backup {
	return predicate.Backup(sql.FieldHasSuffix(FieldFilename, v))
}

// FilenameEqualFold applies the EqualFold predicate on the "filename" field.
func FilenameEqualFold(v string) predicate.Backup {
	return predicate.Backup(sql.FieldEqualFold(FieldFilename, v))
}

// FilenameContainsFold applies the ContainsFold predicate on the "filename" field.
func FilenameContainsFold(v string) predicate.Backup {
	return predicate.Backup(sql.FieldContainsFold(FieldFilename, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Backup {
	return predicate.Backup(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Backup {
	return predicate.Backup(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Backup {
	return predicate.Backup(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Backup {
	return predicate.Backup(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Backup {
	return predicate.Backup(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Backup {
	return predicate.Backup(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Backup {
	return predicate.Backup(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Backup {
	return predicate.Backup(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Backup {
	return predicate.Backup(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Backup {
	return predicate.Backup(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Backup {
	return predicate.Backup(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Backup {
	return predicate.Backup(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Backup {
	return predicate.Backup(sql.FieldContainsFold(FieldContent, v))
}

// SizeBytesEQ applies the EQ predicate on the "size_bytes" field.
func SizeBytesEQ(v int64) predicate.Backup {
	return predicate.Backup(sql.FieldEQ(FieldSizeBytes, v))
}

// SizeBytesNEQ applies the NEQ predicate on the "size_bytes" field.
func SizeBytesNEQ(v int64) predicate.Backup {
	return predicate.Backup(sql.FieldNEQ(FieldSizeBytes, v))
}

// SizeBytesIn applies the In predicate on the "size_bytes" field.
func SizeBytesIn(vs ...int64) predicate.Backup {
	return predicate.Backup(sql.FieldIn(FieldSizeBytes, vs...))
}

// SizeBytesNotIn applies the NotIn predicate on the "size_bytes" field.
func SizeBytesNotIn(vs ...int64) predicate.Backup {
	return predicate.Backup(sql.FieldNotIn(FieldSizeBytes, vs...))
}

// SizeBytesGT applies the GT predicate on the "size_bytes" field.
func SizeBytesGT(v int64) predicate.Backup {
	return predicate.Backup(sql.FieldGT(FieldSizeBytes, v))
}

// SizeBytesGTE applies the GTE predicate on the "size_bytes" field.
func SizeBytesGTE(v int64) predicate.Backup {
	return predicate.Backup(sql.FieldGTE(FieldSizeBytes, v))
}

// SizeBytesLT applies the LT predicate on the "size_bytes" field.
func SizeBytesLT(v int64) predicate.Backup {
	return predicate.Backup(sql.FieldLT(FieldSizeBytes, v))
}

// SizeBytesLTE applies the LTE predicate on the "size_bytes" field.
func SizeBytesLTE(v int64) predicate.Backup {
	return predicate.Backup(sql.FieldLTE(FieldSizeBytes, v))
}

// VendorEQ applies the EQ predicate on the "vendor" field.
func VendorEQ(v string) predicate.Backup {
	return predicate.Backup(sql.FieldEQ(FieldVendor, v))
}

// VendorNEQ applies the NEQ predicate on the "vendor" field.
func VendorNEQ(v string) predicate.Backup {
	return predicate.Backup(sql.FieldNEQ(FieldVendor, v))
}

// VendorIn applies the In predicate on the "vendor" field.
func VendorIn(vs ...string) predicate.Backup {
	return predicate.Backup(sql.FieldIn(FieldVendor, vs...))
}

// VendorNotIn applies the NotIn predicate on the "vendor" field.
func VendorNotIn(vs ...string) predicate.Backup {
	return predicate.Backup(sql.FieldNotIn(FieldVendor, vs...))
}

// VendorGT applies the GT predicate on the "vendor" field.
func VendorGT(v string) predicate.Backup {
	return predicate.Backup(sql.FieldGT(FieldVendor, v))
}

// VendorGTE applies the GTE predicate on the "vendor" field.
func VendorGTE(v string) predicate.Backup {
	return predicate.Backup(sql.FieldGTE(FieldVendor, v))
}

// VendorLT applies the LT predicate on the "vendor" field.
func VendorLT(v string) predicate.Backup {
	return predicate.Backup(sql.FieldLT(FieldVendor, v))
}

// VendorLTE applies the LTE predicate on the "vendor" field.
func VendorLTE(v string) predicate.Backup {
	return predicate.Backup(sql.FieldLTE(FieldVendor, v))
}

// VendorContains applies the Contains predicate on the "vendor" field.
func VendorContains(v string) predicate.Backup {
	return predicate.Backup(sql.FieldContains(FieldVendor, v))
}

// VendorHasPrefix applies the HasPrefix predicate on the "vendor" field.
func VendorHasPrefix(v string) predicate.Backup {
	return predicate.Backup(sql.FieldHasPrefix(FieldVendor, v))
}

// VendorHasSuffix applies the HasSuffix predicate on the "vendor" field.
func VendorHasSuffix(v string) predicate.Backup {
	return predicate.Backup(sql.FieldHasSuffix(FieldVendor, v))
}

// VendorEqualFold applies the EqualFold predicate on the "vendor" field.
func VendorEqualFold(v string) predicate.Backup {
	return predicate.Backup(sql.FieldEqualFold(FieldVendor, v))
}

// VendorContainsFold applies the ContainsFold predicate on the "vendor" field.
func VendorContainsFold(v string) predicate.Backup {
	return predicate.Backup(sql.FieldContainsFold(FieldVendor, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Backup {
	return predicate.Backup(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Backup {
	return predicate.Backup(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Backup {
	return predicate.Backup(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Backup {
	return predicate.Backup(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Backup {
	return predicate.Backup(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Backup {
	return predicate.Backup(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Backup {
	return predicate.Backup(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Backup {
	return predicate.Backup(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Backup) predicate.Backup {
	return predicate.Backup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Backup) predicate.Backup {
	return predicate.Backup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Backup) predicate.Backup {
	return predicate.Backup(sql.NotPredicates(p))
}
