// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/netops/asset-manager/backend/ent/backup"
	"github.com/netops/asset-manager/backend/ent/predicate"
)

// BackupUpdate is the builder for updating Backup entities.
type BackupUpdate struct {
	config
	hooks    []Hook
	mutation *BackupMutation
}

// Where appends a list predicates to the BackupUpdate builder.
func (_u *BackupUpdate) Where(ps ...predicate.Backup) *BackupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeviceIP sets the "device_ip" field.
func (_u *BackupUpdate) SetDeviceIP(v string) *BackupUpdate {
	_u.mutation.SetDeviceIP(v)
	return _u
}

// SetNillableDeviceIP sets the "device_ip" field if the given value is not nil.
func (_u *BackupUpdate) SetNillableDeviceIP(v *string) *BackupUpdate {
	if v != nil {
		_u.SetDeviceIP(*v)
	}
	return _u
}

// SetFilename sets the "filename" field.
func (_u *BackupUpdate) SetFilename(v string) *BackupUpdate {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *BackupUpdate) SetNillableFilename(v *string) *BackupUpdate {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *BackupUpdate) SetContent(v string) *BackupUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *BackupUpdate) SetNillableContent(v *string) *BackupUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *BackupUpdate) SetSizeBytes(v int64) *BackupUpdate {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *BackupUpdate) SetNillableSizeBytes(v *int64) *BackupUpdate {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *BackupUpdate) AddSizeBytes(v int64) *BackupUpdate {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetVendor sets the "vendor" field.
func (_u *BackupUpdate) SetVendor(v string) *BackupUpdate {
	_u.mutation.SetVendor(v)
	return _u
}

// SetNillableVendor sets the "vendor" field if the given value is not nil.
func (_u *BackupUpdate) SetNillableVendor(v *string) *BackupUpdate {
	if v != nil {
		_u.SetVendor(*v)
	}
	return _u
}

// Mutation returns the BackupMutation object of the builder.
func (_u *BackupUpdate) Mutation() *BackupMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BackupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BackupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BackupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BackupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BackupUpdate) check() error {
	if v, ok := _u.mutation.DeviceIP(); ok {
		if err := backup.DeviceIPValidator(v); err != nil {
			return &ValidationError{Name: "device_ip", err: fmt.Errorf(`ent: validator failed for field "Backup.device_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Filename(); ok {
		if err := backup.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "Backup.filename": %w`, err)}
		}
	}
	return nil
}

func (_u *BackupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backup.Table, backup.Columns, sqlgraph.NewFieldSpec(backup.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeviceIP(); ok {
		_spec.SetField(backup.FieldDeviceIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(backup.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(backup.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(backup.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(backup.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Vendor(); ok {
		_spec.SetField(backup.FieldVendor, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BackupUpdateOne is the builder for updating a single Backup entity.
type BackupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BackupMutation
}

// SetDeviceIP sets the "device_ip" field.
func (_u *BackupUpdateOne) SetDeviceIP(v string) *BackupUpdateOne {
	_u.mutation.SetDeviceIP(v)
	return _u
}

// SetNillableDeviceIP sets the "device_ip" field if the given value is not nil.
func (_u *BackupUpdateOne) SetNillableDeviceIP(v *string) *BackupUpdateOne {
	if v != nil {
		_u.SetDeviceIP(*v)
	}
	return _u
}

// SetFilename sets the "filename" field.
func (_u *BackupUpdateOne) SetFilename(v string) *BackupUpdateOne {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *BackupUpdateOne) SetNillableFilename(v *string) *BackupUpdateOne {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *BackupUpdateOne) SetContent(v string) *BackupUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *BackupUpdateOne) SetNillableContent(v *string) *BackupUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *BackupUpdateOne) SetSizeBytes(v int64) *BackupUpdateOne {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *BackupUpdateOne) SetNillableSizeBytes(v *int64) *BackupUpdateOne {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *BackupUpdateOne) AddSizeBytes(v int64) *BackupUpdateOne {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetVendor sets the "vendor" field.
func (_u *BackupUpdateOne) SetVendor(v string) *BackupUpdateOne {
	_u.mutation.SetVendor(v)
	return _u
}

// SetNillableVendor sets the "vendor" field if the given value is not nil.
func (_u *BackupUpdateOne) SetNillableVendor(v *string) *BackupUpdateOne {
	if v != nil {
		_u.SetVendor(*v)
	}
	return _u
}

// Mutation returns the BackupMutation object of the builder.
func (_u *BackupUpdateOne) Mutation() *BackupMutation {
	return _u.mutation
}

// Where appends a list predicates to the BackupUpdate builder.
func (_u *BackupUpdateOne) Where(ps ...predicate.Backup) *BackupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BackupUpdateOne) Select(field string, fields ...string) *BackupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Backup entity.
func (_u *BackupUpdateOne) Save(ctx context.Context) (*Backup, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BackupUpdateOne) SaveX(ctx context.Context) *Backup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BackupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BackupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BackupUpdateOne) check() error {
	if v, ok := _u.mutation.DeviceIP(); ok {
		if err := backup.DeviceIPValidator(v); err != nil {
			return &ValidationError{Name: "device_ip", err: fmt.Errorf(`ent: validator failed for field "Backup.device_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Filename(); ok {
		if err := backup.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "Backup.filename": %w`, err)}
		}
	}
	return nil
}

func (_u *BackupUpdateOne) sqlSave(ctx context.Context) (_node *Backup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backup.Table, backup.Columns, sqlgraph.NewFieldSpec(backup.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Backup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, backup.FieldID)
		for _, f := range fields {
			if !backup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != backup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeviceIP(); ok {
		_spec.SetField(backup.FieldDeviceIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(backup.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(backup.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(backup.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(backup.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Vendor(); ok {
		_spec.SetField(backup.FieldVendor, field.TypeString, value)
	}
	_node = &Backup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
