// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/netops/asset-manager/backend/ent/topologylink"
)

// TopologyLink is the model entity for the TopologyLink schema.
type TopologyLink struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SourceIP holds the value of the "source_ip" field.
	SourceIP string `json:"source_ip,omitempty"`
	// TargetIP holds the value of the "target_ip" field.
	TargetIP string `json:"target_ip,omitempty"`
	// LinkType holds the value of the "link_type" field.
	LinkType string `json:"link_type,omitempty"`
	// Label holds the value of the "label" field.
	Label string `json:"label,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TopologyLink) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case topologylink.FieldID:
			values[i] = new(sql.NullInt64)
		case topologylink.FieldSourceIP, topologylink.FieldTargetIP, topologylink.FieldLinkType, topologylink.FieldLabel:
			values[i] = new(sql.NullString)
		case topologylink.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TopologyLink fields.
func (_m *TopologyLink) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case topologylink.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case topologylink.FieldSourceIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_ip", values[i])
			} else if value.Valid {
				_m.SourceIP = value.String
			}
		case topologylink.FieldTargetIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_ip", values[i])
			} else if value.Valid {
				_m.TargetIP = value.String
			}
		case topologylink.FieldLinkType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field link_type", values[i])
			} else if value.Valid {
				_m.LinkType = value.String
			}
		case topologylink.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = value.String
			}
		case topologylink.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TopologyLink.
// This includes values selected through modifiers, order, etc.
func (_m *TopologyLink) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TopologyLink.
// Note that you need to call TopologyLink.Unwrap() before calling this method if this TopologyLink
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TopologyLink) Update() *TopologyLinkUpdateOne {
	return NewTopologyLinkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TopologyLink entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TopologyLink) Unwrap() *TopologyLink {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TopologyLink is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TopologyLink) String() string {
	var builder strings.Builder
	builder.WriteString("TopologyLink(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("source_ip=")
	builder.WriteString(_m.SourceIP)
	builder.WriteString(", ")
	builder.WriteString("target_ip=")
	builder.WriteString(_m.TargetIP)
	builder.WriteString(", ")
	builder.WriteString("link_type=")
	builder.WriteString(_m.LinkType)
	builder.WriteString(", ")
	builder.WriteString("label=")
	builder.WriteString(_m.Label)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TopologyLinks is a parsable slice of TopologyLink.
type TopologyLinks []*TopologyLink
