// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/netops/asset-manager/backend/ent/predicate"
	"github.com/netops/asset-manager/backend/ent/topologylink"
)

// TopologyLinkUpdate is the builder for updating TopologyLink entities.
type TopologyLinkUpdate struct {
	config
	hooks    []Hook
	mutation *TopologyLinkMutation
}

// Where appends a list predicates to the TopologyLinkUpdate builder.
func (_u *TopologyLinkUpdate) Where(ps ...predicate.TopologyLink) *TopologyLinkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSourceIP sets the "source_ip" field.
func (_u *TopologyLinkUpdate) SetSourceIP(v string) *TopologyLinkUpdate {
	_u.mutation.SetSourceIP(v)
	return _u
}

// SetNillableSourceIP sets the "source_ip" field if the given value is not nil.
func (_u *TopologyLinkUpdate) SetNillableSourceIP(v *string) *TopologyLinkUpdate {
	if v != nil {
		_u.SetSourceIP(*v)
	}
	return _u
}

// SetTargetIP sets the "target_ip" field.
func (_u *TopologyLinkUpdate) SetTargetIP(v string) *TopologyLinkUpdate {
	_u.mutation.SetTargetIP(v)
	return _u
}

// SetNillableTargetIP sets the "target_ip" field if the given value is not nil.
func (_u *TopologyLinkUpdate) SetNillableTargetIP(v *string) *TopologyLinkUpdate {
	if v != nil {
		_u.SetTargetIP(*v)
	}
	return _u
}

// SetLinkType sets the "link_type" field.
func (_u *TopologyLinkUpdate) SetLinkType(v string) *TopologyLinkUpdate {
	_u.mutation.SetLinkType(v)
	return _u
}

// SetNillableLinkType sets the "link_type" field if the given value is not nil.
func (_u *TopologyLinkUpdate) SetNillableLinkType(v *string) *TopologyLinkUpdate {
	if v != nil {
		_u.SetLinkType(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *TopologyLinkUpdate) SetLabel(v string) *TopologyLinkUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *TopologyLinkUpdate) SetNillableLabel(v *string) *TopologyLinkUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// Mutation returns the TopologyLinkMutation object of the builder.
func (_u *TopologyLinkUpdate) Mutation() *TopologyLinkMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TopologyLinkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TopologyLinkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TopologyLinkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TopologyLinkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TopologyLinkUpdate) check() error {
	if v, ok := _u.mutation.SourceIP(); ok {
		if err := topologylink.SourceIPValidator(v); err != nil {
			return &ValidationError{Name: "source_ip", err: fmt.Errorf(`ent: validator failed for field "TopologyLink.source_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetIP(); ok {
		if err := topologylink.TargetIPValidator(v); err != nil {
			return &ValidationError{Name: "target_ip", err: fmt.Errorf(`ent: validator failed for field "TopologyLink.target_ip": %w`, err)}
		}
	}
	return nil
}

func (_u *TopologyLinkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(topologylink.Table, topologylink.Columns, sqlgraph.NewFieldSpec(topologylink.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceIP(); ok {
		_spec.SetField(topologylink.FieldSourceIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetIP(); ok {
		_spec.SetField(topologylink.FieldTargetIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.LinkType(); ok {
		_spec.SetField(topologylink.FieldLinkType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(topologylink.FieldLabel, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{topologylink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TopologyLinkUpdateOne is the builder for updating a single TopologyLink entity.
type TopologyLinkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TopologyLinkMutation
}

// SetSourceIP sets the "source_ip" field.
func (_u *TopologyLinkUpdateOne) SetSourceIP(v string) *TopologyLinkUpdateOne {
	_u.mutation.SetSourceIP(v)
	return _u
}

// SetNillableSourceIP sets the "source_ip" field if the given value is not nil.
func (_u *TopologyLinkUpdateOne) SetNillableSourceIP(v *string) *TopologyLinkUpdateOne {
	if v != nil {
		_u.SetSourceIP(*v)
	}
	return _u
}

// SetTargetIP sets the "target_ip" field.
func (_u *TopologyLinkUpdateOne) SetTargetIP(v string) *TopologyLinkUpdateOne {
	_u.mutation.SetTargetIP(v)
	return _u
}

// SetNillableTargetIP sets the "target_ip" field if the given value is not nil.
func (_u *TopologyLinkUpdateOne) SetNillableTargetIP(v *string) *TopologyLinkUpdateOne {
	if v != nil {
		_u.SetTargetIP(*v)
	}
	return _u
}

// SetLinkType sets the "link_type" field.
func (_u *TopologyLinkUpdateOne) SetLinkType(v string) *TopologyLinkUpdateOne {
	_u.mutation.SetLinkType(v)
	return _u
}

// SetNillableLinkType sets the "link_type" field if the given value is not nil.
func (_u *TopologyLinkUpdateOne) SetNillableLinkType(v *string) *TopologyLinkUpdateOne {
	if v != nil {
		_u.SetLinkType(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *TopologyLinkUpdateOne) SetLabel(v string) *TopologyLinkUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *TopologyLinkUpdateOne) SetNillableLabel(v *string) *TopologyLinkUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// Mutation returns the TopologyLinkMutation object of the builder.
func (_u *TopologyLinkUpdateOne) Mutation() *TopologyLinkMutation {
	return _u.mutation
}

// Where appends a list predicates to the TopologyLinkUpdate builder.
func (_u *TopologyLinkUpdateOne) Where(ps ...predicate.TopologyLink) *TopologyLinkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TopologyLinkUpdateOne) Select(field string, fields ...string) *TopologyLinkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TopologyLink entity.
func (_u *TopologyLinkUpdateOne) Save(ctx context.Context) (*TopologyLink, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TopologyLinkUpdateOne) SaveX(ctx context.Context) *TopologyLink {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TopologyLinkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TopologyLinkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TopologyLinkUpdateOne) check() error {
	if v, ok := _u.mutation.SourceIP(); ok {
		if err := topologylink.SourceIPValidator(v); err != nil {
			return &ValidationError{Name: "source_ip", err: fmt.Errorf(`ent: validator failed for field "TopologyLink.source_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetIP(); ok {
		if err := topologylink.TargetIPValidator(v); err != nil {
			return &ValidationError{Name: "target_ip", err: fmt.Errorf(`ent: validator failed for field "TopologyLink.target_ip": %w`, err)}
		}
	}
	return nil
}

func (_u *TopologyLinkUpdateOne) sqlSave(ctx context.Context) (_node *TopologyLink, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(topologylink.Table, topologylink.Columns, sqlgraph.NewFieldSpec(topologylink.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TopologyLink.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, topologylink.FieldID)
		for _, f := range fields {
			if !topologylink.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != topologylink.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceIP(); ok {
		_spec.SetField(topologylink.FieldSourceIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetIP(); ok {
		_spec.SetField(topologylink.FieldTargetIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.LinkType(); ok {
		_spec.SetField(topologylink.FieldLinkType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(topologylink.FieldLabel, field.TypeString, value)
	}
	_node = &TopologyLink{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{topologylink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
