// Code generated by ent, DO NOT EDIT.

package device

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the device type in the database.
	Label = "device"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIP holds the string denoting the ip field in the database.
	FieldIP = "ip"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldVendor holds the string denoting the vendor field in the database.
	FieldVendor = "vendor"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldLocation holds the string denoting the location field in the database.
	FieldLocation = "location"
	// FieldSn holds the string denoting the sn field in the database.
	FieldSn = "sn"
	// FieldServer holds the string denoting the server field in the database.
	FieldServer = "server"
	// FieldDriver holds the string denoting the driver field in the database.
	FieldDriver = "driver"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldSSHUser holds the string denoting the ssh_user field in the database.
	FieldSSHUser = "ssh_user"
	// FieldSSHPass holds the string denoting the ssh_pass field in the database.
	FieldSSHPass = "ssh_pass"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldLastSeen holds the string denoting the last_seen field in the database.
	FieldLastSeen = "last_seen"
	// FieldGpu holds the string denoting the gpu field in the database.
	FieldGpu = "gpu"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the device in the database.
	Table = "devices"
)

// Columns holds all SQL columns for device fields.
var Columns = []string{
	FieldID,
	FieldIP,
	FieldName,
	FieldVendor,
	FieldModel,
	FieldLocation,
	FieldSn,
	FieldServer,
	FieldDriver,
	FieldTags,
	FieldSSHUser,
	FieldSSHPass,
	FieldStatus,
	FieldLastSeen,
	FieldGpu,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IPValidator is a validator for the "ip" field. It is called by the builders before save.
	IPValidator func(string) error
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultVendor holds the default value on creation for the "vendor" field.
	DefaultVendor string
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
	// DefaultLocation holds the default value on creation for the "location" field.
	DefaultLocation string
	// DefaultSn holds the default value on creation for the "sn" field.
	DefaultSn string
	// DefaultServer holds the default value on creation for the "server" field.
	DefaultServer string
	// DefaultDriver holds the default value on creation for the "driver" field.
	DefaultDriver string
	// DefaultTags holds the default value on creation for the "tags" field.
	DefaultTags []string
	// DefaultSSHUser holds the default value on creation for the "ssh_user" field.
	DefaultSSHUser string
	// DefaultSSHPass holds the default value on creation for the "ssh_pass" field.
	DefaultSSHPass string
	// DefaultGpu holds the default value on creation for the "gpu" field.
	DefaultGpu bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// Status defines the type for the "status" enum field.
type Status string

// StatusUnknown is the default value of the Status enum.
const DefaultStatus = StatusUnknown

// Status values.
const (
	StatusOnline  Status = "online"
	StatusOffline Status = "offline"
	StatusUnknown Status = "unknown"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusOnline, StatusOffline, StatusUnknown:
		return nil
	default:
		return fmt.Errorf("device: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Device queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIP orders the results by the ip field.
func ByIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIP, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByVendor orders the results by the vendor field.
func ByVendor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVendor, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByLocation orders the results by the location field.
func ByLocation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocation, opts...).ToFunc()
}

// BySn orders the results by the sn field.
func BySn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSn, opts...).ToFunc()
}

// ByServer orders the results by the server field.
func ByServer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServer, opts...).ToFunc()
}

// ByDriver orders the results by the driver field.
func ByDriver(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDriver, opts...).ToFunc()
}

// BySSHUser orders the results by the ssh_user field.
func BySSHUser(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSSHUser, opts...).ToFunc()
}

// BySSHPass orders the results by the ssh_pass field.
func BySSHPass(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSSHPass, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByLastSeen orders the results by the last_seen field.
func ByLastSeen(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeen, opts...).ToFunc()
}

// ByGpu orders the results by the gpu field.
func ByGpu(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGpu, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
