// Code generated by ent, DO NOT EDIT.

package device

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/netops/asset-manager/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldID, id))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldIP, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldName, v))
}

// Vendor applies equality check predicate on the "vendor" field. It's identical to VendorEQ.
func Vendor(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldVendor, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldModel, v))
}

// Location applies equality check predicate on the "location" field. It's identical to LocationEQ.
func Location(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldLocation, v))
}

// Sn applies equality check predicate on the "sn" field. It's identical to SnEQ.
func Sn(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldSn, v))
}

// Server applies equality check predicate on the "server" field. It's identical to ServerEQ.
func Server(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldServer, v))
}

// Driver applies equality check predicate on the "driver" field. It's identical to DriverEQ.
func Driver(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldDriver, v))
}

// SSHUser applies equality check predicate on the "ssh_user" field. It's identical to SSHUserEQ.
func SSHUser(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldSSHUser, v))
}

// SSHPass applies equality check predicate on the "ssh_pass" field. It's identical to SSHPassEQ.
func SSHPass(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldSSHPass, v))
}

// LastSeen applies equality check predicate on the "last_seen" field. It's identical to LastSeenEQ.
func LastSeen(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldLastSeen, v))
}

// Gpu applies equality check predicate on the "gpu" field. It's identical to GpuEQ.
func Gpu(v bool) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldGpu, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldUpdatedAt, v))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.Device {
	return predicate.Device(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasSuffix(FieldIP, v))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.Device {
	return predicate.Device(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.Device {
	return predicate.Device(sql.FieldContainsFold(FieldIP, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Device {
	return predicate.Device(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Device {
	return predicate.Device(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Device {
	return predicate.Device(sql.FieldContainsFold(FieldName, v))
}

// VendorEQ applies the EQ predicate on the "vendor" field.
func VendorEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldVendor, v))
}

// VendorNEQ applies the NEQ predicate on the "vendor" field.
func VendorNEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldVendor, v))
}

// VendorIn applies the In predicate on the "vendor" field.
func VendorIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldVendor, vs...))
}

// VendorNotIn applies the NotIn predicate on the "vendor" field.
func VendorNotIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldVendor, vs...))
}

// VendorGT applies the GT predicate on the "vendor" field.
func VendorGT(v string) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldVendor, v))
}

// VendorGTE applies the GTE predicate on the "vendor" field.
func VendorGTE(v string) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldVendor, v))
}

// VendorLT applies the LT predicate on the "vendor" field.
func VendorLT(v string) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldVendor, v))
}

// VendorLTE applies the LTE predicate on the "vendor" field.
func VendorLTE(v string) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldVendor, v))
}

// VendorContains applies the Contains predicate on the "vendor" field.
func VendorContains(v string) predicate.Device {
	return predicate.Device(sql.FieldContains(FieldVendor, v))
}

// VendorHasPrefix applies the HasPrefix predicate on the "vendor" field.
func VendorHasPrefix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasPrefix(FieldVendor, v))
}

// VendorHasSuffix applies the HasSuffix predicate on the "vendor" field.
func VendorHasSuffix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasSuffix(FieldVendor, v))
}

// VendorEqualFold applies the EqualFold predicate on the "vendor" field.
func VendorEqualFold(v string) predicate.Device {
	return predicate.Device(sql.FieldEqualFold(FieldVendor, v))
}

// VendorContainsFold applies the ContainsFold predicate on the "vendor" field.
func VendorContainsFold(v string) predicate.Device {
	return predicate.Device(sql.FieldContainsFold(FieldVendor, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.Device {
	return predicate.Device(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.Device {
	return predicate.Device(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.Device {
	return predicate.Device(sql.FieldContainsFold(FieldModel, v))
}

// LocationEQ applies the EQ predicate on the "location" field.
func LocationEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldLocation, v))
}

// LocationNEQ applies the NEQ predicate on the "location" field.
func LocationNEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldLocation, v))
}

// LocationIn applies the In predicate on the "location" field.
func LocationIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldLocation, vs...))
}

// LocationNotIn applies the NotIn predicate on the "location" field.
func LocationNotIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldLocation, vs...))
}

// LocationGT applies the GT predicate on the "location" field.
func LocationGT(v string) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldLocation, v))
}

// LocationGTE applies the GTE predicate on the "location" field.
func LocationGTE(v string) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldLocation, v))
}

// LocationLT applies the LT predicate on the "location" field.
func LocationLT(v string) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldLocation, v))
}

// LocationLTE applies the LTE predicate on the "location" field.
func LocationLTE(v string) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldLocation, v))
}

// LocationContains applies the Contains predicate on the "location" field.
func LocationContains(v string) predicate.Device {
	return predicate.Device(sql.FieldContains(FieldLocation, v))
}

// LocationHasPrefix applies the HasPrefix predicate on the "location" field.
func LocationHasPrefix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasPrefix(FieldLocation, v))
}

// LocationHasSuffix applies the HasSuffix predicate on the "location" field.
func LocationHasSuffix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasSuffix(FieldLocation, v))
}

// LocationEqualFold applies the EqualFold predicate on the "location" field.
func LocationEqualFold(v string) predicate.Device {
	return predicate.Device(sql.FieldEqualFold(FieldLocation, v))
}

// LocationContainsFold applies the ContainsFold predicate on the "location" field.
func LocationContainsFold(v string) predicate.Device {
	return predicate.Device(sql.FieldContainsFold(FieldLocation, v))
}

// SnEQ applies the EQ predicate on the "sn" field.
func SnEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldSn, v))
}

// SnNEQ applies the NEQ predicate on the "sn" field.
func SnNEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldSn, v))
}

// SnIn applies the In predicate on the "sn" field.
func SnIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldSn, vs...))
}

// SnNotIn applies the NotIn predicate on the "sn" field.
func SnNotIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldSn, vs...))
}

// SnGT applies the GT predicate on the "sn" field.
func SnGT(v string) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldSn, v))
}

// SnGTE applies the GTE predicate on the "sn" field.
func SnGTE(v string) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldSn, v))
}

// SnLT applies the LT predicate on the "sn" field.
func SnLT(v string) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldSn, v))
}

// SnLTE applies the LTE predicate on the "sn" field.
func SnLTE(v string) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldSn, v))
}

// SnContains applies the Contains predicate on the "sn" field.
func SnContains(v string) predicate.Device {
	return predicate.Device(sql.FieldContains(FieldSn, v))
}

// SnHasPrefix applies the HasPrefix predicate on the "sn" field.
func SnHasPrefix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasPrefix(FieldSn, v))
}

// SnHasSuffix applies the HasSuffix predicate on the "sn" field.
func SnHasSuffix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasSuffix(FieldSn, v))
}

// SnEqualFold applies the EqualFold predicate on the "sn" field.
func SnEqualFold(v string) predicate.Device {
	return predicate.Device(sql.FieldEqualFold(FieldSn, v))
}

// SnContainsFold applies the ContainsFold predicate on the "sn" field.
func SnContainsFold(v string) predicate.Device {
	return predicate.Device(sql.FieldContainsFold(FieldSn, v))
}

// ServerEQ applies the EQ predicate on the "server" field.
func ServerEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldServer, v))
}

// ServerNEQ applies the NEQ predicate on the "server" field.
func ServerNEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldServer, v))
}

// ServerIn applies the In predicate on the "server" field.
func ServerIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldServer, vs...))
}

// ServerNotIn applies the NotIn predicate on the "server" field.
func ServerNotIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldServer, vs...))
}

// ServerGT applies the GT predicate on the "server" field.
func ServerGT(v string) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldServer, v))
}

// ServerGTE applies the GTE predicate on the "server" field.
func ServerGTE(v string) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldServer, v))
}

// ServerLT applies the LT predicate on the "server" field.
func ServerLT(v string) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldServer, v))
}

// ServerLTE applies the LTE predicate on the "server" field.
func ServerLTE(v string) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldServer, v))
}

// ServerContains applies the Contains predicate on the "server" field.
func ServerContains(v string) predicate.Device {
	return predicate.Device(sql.FieldContains(FieldServer, v))
}

// ServerHasPrefix applies the HasPrefix predicate on the "server" field.
func ServerHasPrefix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasPrefix(FieldServer, v))
}

// ServerHasSuffix applies the HasSuffix predicate on the "server" field.
func ServerHasSuffix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasSuffix(FieldServer, v))
}

// ServerEqualFold applies the EqualFold predicate on the "server" field.
func ServerEqualFold(v string) predicate.Device {
	return predicate.Device(sql.FieldEqualFold(FieldServer, v))
}

// ServerContainsFold applies the ContainsFold predicate on the "server" field.
func ServerContainsFold(v string) predicate.Device {
	return predicate.Device(sql.FieldContainsFold(FieldServer, v))
}

// DriverEQ applies the EQ predicate on the "driver" field.
func DriverEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldDriver, v))
}

// DriverNEQ applies the NEQ predicate on the "driver" field.
func DriverNEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldDriver, v))
}

// DriverIn applies the In predicate on the "driver" field.
func DriverIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldDriver, vs...))
}

// DriverNotIn applies the NotIn predicate on the "driver" field.
func DriverNotIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldDriver, vs...))
}

// DriverGT applies the GT predicate on the "driver" field.
func DriverGT(v string) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldDriver, v))
}

// DriverGTE applies the GTE predicate on the "driver" field.
func DriverGTE(v string) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldDriver, v))
}

// DriverLT applies the LT predicate on the "driver" field.
func DriverLT(v string) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldDriver, v))
}

// DriverLTE applies the LTE predicate on the "driver" field.
func DriverLTE(v string) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldDriver, v))
}

// DriverContains applies the Contains predicate on the "driver" field.
func DriverContains(v string) predicate.Device {
	return predicate.Device(sql.FieldContains(FieldDriver, v))
}

// DriverHasPrefix applies the HasPrefix predicate on the "driver" field.
func DriverHasPrefix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasPrefix(FieldDriver, v))
}

// DriverHasSuffix applies the HasSuffix predicate on the "driver" field.
func DriverHasSuffix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasSuffix(FieldDriver, v))
}

// DriverEqualFold applies the EqualFold predicate on the "driver" field.
func DriverEqualFold(v string) predicate.Device {
	return predicate.Device(sql.FieldEqualFold(FieldDriver, v))
}

// DriverContainsFold applies the ContainsFold predicate on the "driver" field.
func DriverContainsFold(v string) predicate.Device {
	return predicate.Device(sql.FieldContainsFold(FieldDriver, v))
}

// SSHUserEQ applies the EQ predicate on the "ssh_user" field.
func SSHUserEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldSSHUser, v))
}

// SSHUserNEQ applies the NEQ predicate on the "ssh_user" field.
func SSHUserNEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldSSHUser, v))
}

// SSHUserIn applies the In predicate on the "ssh_user" field.
func SSHUserIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldSSHUser, vs...))
}

// SSHUserNotIn applies the NotIn predicate on the "ssh_user" field.
func SSHUserNotIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldSSHUser, vs...))
}

// SSHUserGT applies the GT predicate on the "ssh_user" field.
func SSHUserGT(v string) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldSSHUser, v))
}

// SSHUserGTE applies the GTE predicate on the "ssh_user" field.
func SSHUserGTE(v string) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldSSHUser, v))
}

// SSHUserLT applies the LT predicate on the "ssh_user" field.
func SSHUserLT(v string) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldSSHUser, v))
}

// SSHUserLTE applies the LTE predicate on the "ssh_user" field.
func SSHUserLTE(v string) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldSSHUser, v))
}

// SSHUserContains applies the Contains predicate on the "ssh_user" field.
func SSHUserContains(v string) predicate.Device {
	return predicate.Device(sql.FieldContains(FieldSSHUser, v))
}

// SSHUserHasPrefix applies the HasPrefix predicate on the "ssh_user" field.
func SSHUserHasPrefix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasPrefix(FieldSSHUser, v))
}

// SSHUserHasSuffix applies the HasSuffix predicate on the "ssh_user" field.
func SSHUserHasSuffix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasSuffix(FieldSSHUser, v))
}

// SSHUserEqualFold applies the EqualFold predicate on the "ssh_user" field.
func SSHUserEqualFold(v string) predicate.Device {
	return predicate.Device(sql.FieldEqualFold(FieldSSHUser, v))
}

// SSHUserContainsFold applies the ContainsFold predicate on the "ssh_user" field.
func SSHUserContainsFold(v string) predicate.Device {
	return predicate.Device(sql.FieldContainsFold(FieldSSHUser, v))
}

// SSHPassEQ applies the EQ predicate on the "ssh_pass" field.
func SSHPassEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldSSHPass, v))
}

// SSHPassNEQ applies the NEQ predicate on the "ssh_pass" field.
func SSHPassNEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldSSHPass, v))
}

// SSHPassIn applies the In predicate on the "ssh_pass" field.
func SSHPassIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldSSHPass, vs...))
}

// SSHPassNotIn applies the NotIn predicate on the "ssh_pass" field.
func SSHPassNotIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldSSHPass, vs...))
}

// SSHPassGT applies the GT predicate on the "ssh_pass" field.
func SSHPassGT(v string) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldSSHPass, v))
}

// SSHPassGTE applies the GTE predicate on the "ssh_pass" field.
func SSHPassGTE(v string) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldSSHPass, v))
}

// SSHPassLT applies the LT predicate on the "ssh_pass" field.
func SSHPassLT(v string) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldSSHPass, v))
}

// SSHPassLTE applies the LTE predicate on the "ssh_pass" field.
func SSHPassLTE(v string) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldSSHPass, v))
}

// SSHPassContains applies the Contains predicate on the "ssh_pass" field.
func SSHPassContains(v string) predicate.Device {
	return predicate.Device(sql.FieldContains(FieldSSHPass, v))
}

// SSHPassHasPrefix applies the HasPrefix predicate on the "ssh_pass" field.
func SSHPassHasPrefix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasPrefix(FieldSSHPass, v))
}

// SSHPassHasSuffix applies the HasSuffix predicate on the "ssh_pass" field.
func SSHPassHasSuffix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasSuffix(FieldSSHPass, v))
}

// SSHPassEqualFold applies the EqualFold predicate on the "ssh_pass" field.
func SSHPassEqualFold(v string) predicate.Device {
	return predicate.Device(sql.FieldEqualFold(FieldSSHPass, v))
}

// SSHPassContainsFold applies the ContainsFold predicate on the "ssh_pass" field.
func SSHPassContainsFold(v string) predicate.Device {
	return predicate.Device(sql.FieldContainsFold(FieldSSHPass, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldStatus, vs...))
}

// LastSeenEQ applies the EQ predicate on the "last_seen" field.
func LastSeenEQ(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldLastSeen, v))
}

// LastSeenNEQ applies the NEQ predicate on the "last_seen" field.
func LastSeenNEQ(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldLastSeen, v))
}

// LastSeenIn applies the In predicate on the "last_seen" field.
func LastSeenIn(vs ...time.Time) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldLastSeen, vs...))
}

// LastSeenNotIn applies the NotIn predicate on the "last_seen" field.
func LastSeenNotIn(vs ...time.Time) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldLastSeen, vs...))
}

// LastSeenGT applies the GT predicate on the "last_seen" field.
func LastSeenGT(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldLastSeen, v))
}

// LastSeenGTE applies the GTE predicate on the "last_seen" field.
func LastSeenGTE(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldLastSeen, v))
}

// LastSeenLT applies the LT predicate on the "last_seen" field.
func LastSeenLT(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldLastSeen, v))
}

// LastSeenLTE applies the LTE predicate on the "last_seen" field.
func LastSeenLTE(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldLastSeen, v))
}

// LastSeenIsNil applies the IsNil predicate on the "last_seen" field.
func LastSeenIsNil() predicate.Device {
	return predicate.Device(sql.FieldIsNull(FieldLastSeen))
}

// LastSeenNotNil applies the NotNil predicate on the "last_seen" field.
func LastSeenNotNil() predicate.Device {
	return predicate.Device(sql.FieldNotNull(FieldLastSeen))
}

// GpuEQ applies the EQ predicate on the "gpu" field.
func GpuEQ(v bool) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldGpu, v))
}

// GpuNEQ applies the NEQ predicate on the "gpu" field.
func GpuNEQ(v bool) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldGpu, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Device) predicate.Device {
	return predicate.Device(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Device) predicate.Device {
	return predicate.Device(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Device) predicate.Device {
	return predicate.Device(sql.NotPredicates(p))
}
