// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BackupsColumns holds the columns for the "backups" table.
	BackupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "device_ip", Type: field.TypeString},
		{Name: "filename", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "size_bytes", Type: field.TypeInt64, Default: 0},
		{Name: "vendor", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
	}
	// BackupsTable holds the schema information for the "backups" table.
	BackupsTable = &schema.Table{
		Name:       "backups",
		Columns:    BackupsColumns,
		PrimaryKey: []*schema.Column{BackupsColumns[0]},
	}
	// DevicesColumns holds the columns for the "devices" table.
	DevicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ip", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "vendor", Type: field.TypeString, Default: ""},
		{Name: "model", Type: field.TypeString, Default: ""},
		{Name: "location", Type: field.TypeString, Default: ""},
		{Name: "sn", Type: field.TypeString, Default: ""},
		{Name: "server", Type: field.TypeString, Default: ""},
		{Name: "driver", Type: field.TypeString, Default: ""},
		{Name: "tags", Type: field.TypeJSON},
		{Name: "ssh_user", Type: field.TypeString, Default: "root"},
		{Name: "ssh_pass", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"online", "offline", "unknown"}, Default: "unknown"},
		{Name: "last_seen", Type: field.TypeTime, Nullable: true},
		{Name: "gpu", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// DevicesTable holds the schema information for the "devices" table.
	DevicesTable = &schema.Table{
		Name:       "devices",
		Columns:    DevicesColumns,
		PrimaryKey: []*schema.Column{DevicesColumns[0]},
	}
	// TopologyLinksColumns holds the columns for the "topology_links" table.
	TopologyLinksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "source_ip", Type: field.TypeString},
		{Name: "target_ip", Type: field.TypeString},
		{Name: "link_type", Type: field.TypeString, Default: "logical"},
		{Name: "label", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
	}
	// TopologyLinksTable holds the schema information for the "topology_links" table.
	TopologyLinksTable = &schema.Table{
		Name:       "topology_links",
		Columns:    TopologyLinksColumns,
		PrimaryKey: []*schema.Column{TopologyLinksColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"root", "operator", "viewer"}, Default: "operator"},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BackupsTable,
		DevicesTable,
		TopologyLinksTable,
		UsersTable,
	}
)

func init() {
}
