// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/netops/asset-manager/ent/device"
)

// DeviceCreate is the builder for creating a Device entity.
type DeviceCreate struct {
	config
	mutation *DeviceMutation
	hooks    []Hook
}

// SetIP sets the "ip" field.
func (_c *DeviceCreate) SetIP(v string) *DeviceCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetName sets the "name" field.
func (_c *DeviceCreate) SetName(v string) *DeviceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableName(v *string) *DeviceCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetVendor sets the "vendor" field.
func (_c *DeviceCreate) SetVendor(v string) *DeviceCreate {
	_c.mutation.SetVendor(v)
	return _c
}

// SetNillableVendor sets the "vendor" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableVendor(v *string) *DeviceCreate {
	if v != nil {
		_c.SetVendor(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *DeviceCreate) SetModel(v string) *DeviceCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableModel(v *string) *DeviceCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetLocation sets the "location" field.
func (_c *DeviceCreate) SetLocation(v string) *DeviceCreate {
	_c.mutation.SetLocation(v)
	return _c
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableLocation(v *string) *DeviceCreate {
	if v != nil {
		_c.SetLocation(*v)
	}
	return _c
}

// SetSn sets the "sn" field.
func (_c *DeviceCreate) SetSn(v string) *DeviceCreate {
	_c.mutation.SetSn(v)
	return _c
}

// SetNillableSn sets the "sn" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableSn(v *string) *DeviceCreate {
	if v != nil {
		_c.SetSn(*v)
	}
	return _c
}

// SetServer sets the "server" field.
func (_c *DeviceCreate) SetServer(v string) *DeviceCreate {
	_c.mutation.SetServer(v)
	return _c
}

// SetNillableServer sets the "server" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableServer(v *string) *DeviceCreate {
	if v != nil {
		_c.SetServer(*v)
	}
	return _c
}

// SetDriver sets the "driver" field.
func (_c *DeviceCreate) SetDriver(v string) *DeviceCreate {
	_c.mutation.SetDriver(v)
	return _c
}

// SetNillableDriver sets the "driver" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableDriver(v *string) *DeviceCreate {
	if v != nil {
		_c.SetDriver(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *DeviceCreate) SetTags(v []string) *DeviceCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetSSHUser sets the "ssh_user" field.
func (_c *DeviceCreate) SetSSHUser(v string) *DeviceCreate {
	_c.mutation.SetSSHUser(v)
	return _c
}

// SetNillableSSHUser sets the "ssh_user" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableSSHUser(v *string) *DeviceCreate {
	if v != nil {
		_c.SetSSHUser(*v)
	}
	return _c
}

// SetSSHPass sets the "ssh_pass" field.
func (_c *DeviceCreate) SetSSHPass(v string) *DeviceCreate {
	_c.mutation.SetSSHPass(v)
	return _c
}

// SetNillableSSHPass sets the "ssh_pass" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableSSHPass(v *string) *DeviceCreate {
	if v != nil {
		_c.SetSSHPass(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *DeviceCreate) SetStatus(v device.Status) *DeviceCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableStatus(v *device.Status) *DeviceCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLastSeen sets the "last_seen" field.
func (_c *DeviceCreate) SetLastSeen(v time.Time) *DeviceCreate {
	_c.mutation.SetLastSeen(v)
	return _c
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableLastSeen(v *time.Time) *DeviceCreate {
	if v != nil {
		_c.SetLastSeen(*v)
	}
	return _c
}

// SetGpu sets the "gpu" field.
func (_c *DeviceCreate) SetGpu(v bool) *DeviceCreate {
	_c.mutation.SetGpu(v)
	return _c
}

// SetNillableGpu sets the "gpu" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableGpu(v *bool) *DeviceCreate {
	if v != nil {
		_c.SetGpu(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeviceCreate) SetCreatedAt(v time.Time) *DeviceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableCreatedAt(v *time.Time) *DeviceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DeviceCreate) SetUpdatedAt(v time.Time) *DeviceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableUpdatedAt(v *time.Time) *DeviceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DeviceCreate) SetID(v int) *DeviceCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the DeviceMutation object of the builder.
func (_c *DeviceCreate) Mutation() *DeviceMutation {
	return _c.mutation
}

// Save creates the Device in the database.
func (_c *DeviceCreate) Save(ctx context.Context) (*Device, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeviceCreate) SaveX(ctx context.Context) *Device {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeviceCreate) defaults() {
	if _, ok := _c.mutation.Name(); !ok {
		v := device.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.Vendor(); !ok {
		v := device.DefaultVendor
		_c.mutation.SetVendor(v)
	}
	if _, ok := _c.mutation.Model(); !ok {
		v := device.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.Location(); !ok {
		v := device.DefaultLocation
		_c.mutation.SetLocation(v)
	}
	if _, ok := _c.mutation.Sn(); !ok {
		v := device.DefaultSn
		_c.mutation.SetSn(v)
	}
	if _, ok := _c.mutation.Server(); !ok {
		v := device.DefaultServer
		_c.mutation.SetServer(v)
	}
	if _, ok := _c.mutation.Driver(); !ok {
		v := device.DefaultDriver
		_c.mutation.SetDriver(v)
	}
	if _, ok := _c.mutation.Tags(); !ok {
		v := device.DefaultTags
		_c.mutation.SetTags(v)
	}
	if _, ok := _c.mutation.SSHUser(); !ok {
		v := device.DefaultSSHUser
		_c.mutation.SetSSHUser(v)
	}
	if _, ok := _c.mutation.SSHPass(); !ok {
		v := device.DefaultSSHPass
		_c.mutation.SetSSHPass(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := device.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Gpu(); !ok {
		v := device.DefaultGpu
		_c.mutation.SetGpu(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := device.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := device.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeviceCreate) check() error {
	if _, ok := _c.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "Device.ip"`)}
	}
	if v, ok := _c.mutation.IP(); ok {
		if err := device.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Device.ip": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Device.name"`)}
	}
	if _, ok := _c.mutation.Vendor(); !ok {
		return &ValidationError{Name: "vendor", err: errors.New(`ent: missing required field "Device.vendor"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "Device.model"`)}
	}
	if _, ok := _c.mutation.Location(); !ok {
		return &ValidationError{Name: "location", err: errors.New(`ent: missing required field "Device.location"`)}
	}
	if _, ok := _c.mutation.Sn(); !ok {
		return &ValidationError{Name: "sn", err: errors.New(`ent: missing required field "Device.sn"`)}
	}
	if _, ok := _c.mutation.Server(); !ok {
		return &ValidationError{Name: "server", err: errors.New(`ent: missing required field "Device.server"`)}
	}
	if _, ok := _c.mutation.Driver(); !ok {
		return &ValidationError{Name: "driver", err: errors.New(`ent: missing required field "Device.driver"`)}
	}
	if _, ok := _c.mutation.Tags(); !ok {
		return &ValidationError{Name: "tags", err: errors.New(`ent: missing required field "Device.tags"`)}
	}
	if _, ok := _c.mutation.SSHUser(); !ok {
		return &ValidationError{Name: "ssh_user", err: errors.New(`ent: missing required field "Device.ssh_user"`)}
	}
	if _, ok := _c.mutation.SSHPass(); !ok {
		return &ValidationError{Name: "ssh_pass", err: errors.New(`ent: missing required field "Device.ssh_pass"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Device.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := device.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Device.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Gpu(); !ok {
		return &ValidationError{Name: "gpu", err: errors.New(`ent: missing required field "Device.gpu"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Device.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Device.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := device.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Device.id": %w`, err)}
		}
	}
	return nil
}

func (_c *DeviceCreate) sqlSave(ctx context.Context) (*Device, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeviceCreate) createSpec() (*Device, *sqlgraph.CreateSpec) {
	var (
		_node = &Device{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(device.Table, sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(device.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(device.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Vendor(); ok {
		_spec.SetField(device.FieldVendor, field.TypeString, value)
		_node.Vendor = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(device.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Location(); ok {
		_spec.SetField(device.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := _c.mutation.Sn(); ok {
		_spec.SetField(device.FieldSn, field.TypeString, value)
		_node.Sn = value
	}
	if value, ok := _c.mutation.Server(); ok {
		_spec.SetField(device.FieldServer, field.TypeString, value)
		_node.Server = value
	}
	if value, ok := _c.mutation.Driver(); ok {
		_spec.SetField(device.FieldDriver, field.TypeString, value)
		_node.Driver = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(device.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.SSHUser(); ok {
		_spec.SetField(device.FieldSSHUser, field.TypeString, value)
		_node.SSHUser = value
	}
	if value, ok := _c.mutation.SSHPass(); ok {
		_spec.SetField(device.FieldSSHPass, field.TypeString, value)
		_node.SSHPass = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(device.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LastSeen(); ok {
		_spec.SetField(device.FieldLastSeen, field.TypeTime, value)
		_node.LastSeen = &value
	}
	if value, ok := _c.mutation.Gpu(); ok {
		_spec.SetField(device.FieldGpu, field.TypeBool, value)
		_node.Gpu = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(device.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// DeviceCreateBulk is the builder for creating many Device entities in bulk.
type DeviceCreateBulk struct {
	config
	err      error
	builders []*DeviceCreate
}

// Save creates the Device entities in the database.
func (_c *DeviceCreateBulk) Save(ctx context.Context) ([]*Device, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Device, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeviceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeviceCreateBulk) SaveX(ctx context.Context) []*Device {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
