// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/netops/asset-manager/ent/device"
	"github.com/netops/asset-manager/ent/predicate"
)

// DeviceUpdate is the builder for updating Device entities.
type DeviceUpdate struct {
	config
	hooks    []Hook
	mutation *DeviceMutation
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdate) Where(ps ...predicate.Device) *DeviceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetIP sets the "ip" field.
func (_u *DeviceUpdate) SetIP(v string) *DeviceUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableIP(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DeviceUpdate) SetName(v string) *DeviceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableName(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVendor sets the "vendor" field.
func (_u *DeviceUpdate) SetVendor(v string) *DeviceUpdate {
	_u.mutation.SetVendor(v)
	return _u
}

// SetNillableVendor sets the "vendor" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableVendor(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetVendor(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *DeviceUpdate) SetModel(v string) *DeviceUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableModel(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetLocation sets the "location" field.
func (_u *DeviceUpdate) SetLocation(v string) *DeviceUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableLocation(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetSn sets the "sn" field.
func (_u *DeviceUpdate) SetSn(v string) *DeviceUpdate {
	_u.mutation.SetSn(v)
	return _u
}

// SetNillableSn sets the "sn" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableSn(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetSn(*v)
	}
	return _u
}

// SetServer sets the "server" field.
func (_u *DeviceUpdate) SetServer(v string) *DeviceUpdate {
	_u.mutation.SetServer(v)
	return _u
}

// SetNillableServer sets the "server" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableServer(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetServer(*v)
	}
	return _u
}

// SetDriver sets the "driver" field.
func (_u *DeviceUpdate) SetDriver(v string) *DeviceUpdate {
	_u.mutation.SetDriver(v)
	return _u
}

// SetNillableDriver sets the "driver" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableDriver(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetDriver(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *DeviceUpdate) SetTags(v []string) *DeviceUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *DeviceUpdate) AppendTags(v []string) *DeviceUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// SetSSHUser sets the "ssh_user" field.
func (_u *DeviceUpdate) SetSSHUser(v string) *DeviceUpdate {
	_u.mutation.SetSSHUser(v)
	return _u
}

// SetNillableSSHUser sets the "ssh_user" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableSSHUser(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetSSHUser(*v)
	}
	return _u
}

// SetSSHPass sets the "ssh_pass" field.
func (_u *DeviceUpdate) SetSSHPass(v string) *DeviceUpdate {
	_u.mutation.SetSSHPass(v)
	return _u
}

// SetNillableSSHPass sets the "ssh_pass" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableSSHPass(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetSSHPass(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DeviceUpdate) SetStatus(v device.Status) *DeviceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableStatus(v *device.Status) *DeviceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastSeen sets the "last_seen" field.
func (_u *DeviceUpdate) SetLastSeen(v time.Time) *DeviceUpdate {
	_u.mutation.SetLastSeen(v)
	return _u
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableLastSeen(v *time.Time) *DeviceUpdate {
	if v != nil {
		_u.SetLastSeen(*v)
	}
	return _u
}

// ClearLastSeen clears the value of the "last_seen" field.
func (_u *DeviceUpdate) ClearLastSeen() *DeviceUpdate {
	_u.mutation.ClearLastSeen()
	return _u
}

// SetGpu sets the "gpu" field.
func (_u *DeviceUpdate) SetGpu(v bool) *DeviceUpdate {
	_u.mutation.SetGpu(v)
	return _u
}

// SetNillableGpu sets the "gpu" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableGpu(v *bool) *DeviceUpdate {
	if v != nil {
		_u.SetGpu(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeviceUpdate) SetUpdatedAt(v time.Time) *DeviceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdate) Mutation() *DeviceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeviceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeviceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeviceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := device.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdate) check() error {
	if v, ok := _u.mutation.IP(); ok {
		if err := device.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Device.ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := device.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Device.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DeviceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(device.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(device.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Vendor(); ok {
		_spec.SetField(device.FieldVendor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(device.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(device.FieldLocation, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sn(); ok {
		_spec.SetField(device.FieldSn, field.TypeString, value)
	}
	if value, ok := _u.mutation.Server(); ok {
		_spec.SetField(device.FieldServer, field.TypeString, value)
	}
	if value, ok := _u.mutation.Driver(); ok {
		_spec.SetField(device.FieldDriver, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(device.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, device.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.SSHUser(); ok {
		_spec.SetField(device.FieldSSHUser, field.TypeString, value)
	}
	if value, ok := _u.mutation.SSHPass(); ok {
		_spec.SetField(device.FieldSSHPass, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(device.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastSeen(); ok {
		_spec.SetField(device.FieldLastSeen, field.TypeTime, value)
	}
	if _u.mutation.LastSeenCleared() {
		_spec.ClearField(device.FieldLastSeen, field.TypeTime)
	}
	if value, ok := _u.mutation.Gpu(); ok {
		_spec.SetField(device.FieldGpu, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeviceUpdateOne is the builder for updating a single Device entity.
type DeviceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeviceMutation
}

// SetIP sets the "ip" field.
func (_u *DeviceUpdateOne) SetIP(v string) *DeviceUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableIP(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DeviceUpdateOne) SetName(v string) *DeviceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableName(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVendor sets the "vendor" field.
func (_u *DeviceUpdateOne) SetVendor(v string) *DeviceUpdateOne {
	_u.mutation.SetVendor(v)
	return _u
}

// SetNillableVendor sets the "vendor" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableVendor(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetVendor(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *DeviceUpdateOne) SetModel(v string) *DeviceUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableModel(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetLocation sets the "location" field.
func (_u *DeviceUpdateOne) SetLocation(v string) *DeviceUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableLocation(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetSn sets the "sn" field.
func (_u *DeviceUpdateOne) SetSn(v string) *DeviceUpdateOne {
	_u.mutation.SetSn(v)
	return _u
}

// SetNillableSn sets the "sn" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableSn(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetSn(*v)
	}
	return _u
}

// SetServer sets the "server" field.
func (_u *DeviceUpdateOne) SetServer(v string) *DeviceUpdateOne {
	_u.mutation.SetServer(v)
	return _u
}

// SetNillableServer sets the "server" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableServer(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetServer(*v)
	}
	return _u
}

// SetDriver sets the "driver" field.
func (_u *DeviceUpdateOne) SetDriver(v string) *DeviceUpdateOne {
	_u.mutation.SetDriver(v)
	return _u
}

// SetNillableDriver sets the "driver" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableDriver(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetDriver(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *DeviceUpdateOne) SetTags(v []string) *DeviceUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *DeviceUpdateOne) AppendTags(v []string) *DeviceUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// SetSSHUser sets the "ssh_user" field.
func (_u *DeviceUpdateOne) SetSSHUser(v string) *DeviceUpdateOne {
	_u.mutation.SetSSHUser(v)
	return _u
}

// SetNillableSSHUser sets the "ssh_user" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableSSHUser(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetSSHUser(*v)
	}
	return _u
}

// SetSSHPass sets the "ssh_pass" field.
func (_u *DeviceUpdateOne) SetSSHPass(v string) *DeviceUpdateOne {
	_u.mutation.SetSSHPass(v)
	return _u
}

// SetNillableSSHPass sets the "ssh_pass" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableSSHPass(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetSSHPass(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DeviceUpdateOne) SetStatus(v device.Status) *DeviceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableStatus(v *device.Status) *DeviceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastSeen sets the "last_seen" field.
func (_u *DeviceUpdateOne) SetLastSeen(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetLastSeen(v)
	return _u
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableLastSeen(v *time.Time) *DeviceUpdateOne {
	if v != nil {
		_u.SetLastSeen(*v)
	}
	return _u
}

// ClearLastSeen clears the value of the "last_seen" field.
func (_u *DeviceUpdateOne) ClearLastSeen() *DeviceUpdateOne {
	_u.mutation.ClearLastSeen()
	return _u
}

// SetGpu sets the "gpu" field.
func (_u *DeviceUpdateOne) SetGpu(v bool) *DeviceUpdateOne {
	_u.mutation.SetGpu(v)
	return _u
}

// SetNillableGpu sets the "gpu" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableGpu(v *bool) *DeviceUpdateOne {
	if v != nil {
		_u.SetGpu(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeviceUpdateOne) SetUpdatedAt(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdateOne) Mutation() *DeviceMutation {
	return _u.mutation
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdateOne) Where(ps ...predicate.Device) *DeviceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeviceUpdateOne) Select(field string, fields ...string) *DeviceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Device entity.
func (_u *DeviceUpdateOne) Save(ctx context.Context) (*Device, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdateOne) SaveX(ctx context.Context) *Device {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeviceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeviceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := device.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdateOne) check() error {
	if v, ok := _u.mutation.IP(); ok {
		if err := device.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Device.ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := device.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Device.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DeviceUpdateOne) sqlSave(ctx context.Context) (_node *Device, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Device.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, device.FieldID)
		for _, f := range fields {
			if !device.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != device.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(device.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(device.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Vendor(); ok {
		_spec.SetField(device.FieldVendor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(device.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(device.FieldLocation, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sn(); ok {
		_spec.SetField(device.FieldSn, field.TypeString, value)
	}
	if value, ok := _u.mutation.Server(); ok {
		_spec.SetField(device.FieldServer, field.TypeString, value)
	}
	if value, ok := _u.mutation.Driver(); ok {
		_spec.SetField(device.FieldDriver, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(device.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, device.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.SSHUser(); ok {
		_spec.SetField(device.FieldSSHUser, field.TypeString, value)
	}
	if value, ok := _u.mutation.SSHPass(); ok {
		_spec.SetField(device.FieldSSHPass, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(device.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastSeen(); ok {
		_spec.SetField(device.FieldLastSeen, field.TypeTime, value)
	}
	if _u.mutation.LastSeenCleared() {
		_spec.ClearField(device.FieldLastSeen, field.TypeTime)
	}
	if value, ok := _u.mutation.Gpu(); ok {
		_spec.SetField(device.FieldGpu, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Device{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
