// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/netops/asset-manager/ent/backup"
	"github.com/netops/asset-manager/ent/device"
	"github.com/netops/asset-manager/ent/schema"
	"github.com/netops/asset-manager/ent/topologylink"
	"github.com/netops/asset-manager/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	backupFields := schema.Backup{}.Fields()
	_ = backupFields
	// backupDescDeviceIP is the schema descriptor for device_ip field.
	backupDescDeviceIP := backupFields[1].Descriptor()
	// backup.DeviceIPValidator is a validator for the "device_ip" field. It is called by the builders before save.
	backup.DeviceIPValidator = backupDescDeviceIP.Validators[0].(func(string) error)
	// backupDescFilename is the schema descriptor for filename field.
	backupDescFilename := backupFields[2].Descriptor()
	// backup.FilenameValidator is a validator for the "filename" field. It is called by the builders before save.
	backup.FilenameValidator = backupDescFilename.Validators[0].(func(string) error)
	// backupDescContent is the schema descriptor for content field.
	backupDescContent := backupFields[3].Descriptor()
	// backup.DefaultContent holds the default value on creation for the content field.
	backup.DefaultContent = backupDescContent.Default.(string)
	// backupDescSizeBytes is the schema descriptor for size_bytes field.
	backupDescSizeBytes := backupFields[4].Descriptor()
	// backup.DefaultSizeBytes holds the default value on creation for the size_bytes field.
	backup.DefaultSizeBytes = backupDescSizeBytes.Default.(int64)
	// backupDescVendor is the schema descriptor for vendor field.
	backupDescVendor := backupFields[5].Descriptor()
	// backup.DefaultVendor holds the default value on creation for the vendor field.
	backup.DefaultVendor = backupDescVendor.Default.(string)
	// backupDescCreatedAt is the schema descriptor for created_at field.
	backupDescCreatedAt := backupFields[6].Descriptor()
	// backup.DefaultCreatedAt holds the default value on creation for the created_at field.
	backup.DefaultCreatedAt = backupDescCreatedAt.Default.(func() time.Time)
	// backupDescID is the schema descriptor for id field.
	backupDescID := backupFields[0].Descriptor()
	// backup.IDValidator is a validator for the "id" field. It is called by the builders before save.
	backup.IDValidator = backupDescID.Validators[0].(func(int) error)
	deviceFields := schema.Device{}.Fields()
	_ = deviceFields
	// deviceDescIP is the schema descriptor for ip field.
	deviceDescIP := deviceFields[1].Descriptor()
	// device.IPValidator is a validator for the "ip" field. It is called by the builders before save.
	device.IPValidator = deviceDescIP.Validators[0].(func(string) error)
	// deviceDescName is the schema descriptor for name field.
	deviceDescName := deviceFields[2].Descriptor()
	// device.DefaultName holds the default value on creation for the name field.
	device.DefaultName = deviceDescName.Default.(string)
	// deviceDescVendor is the schema descriptor for vendor field.
	deviceDescVendor := deviceFields[3].Descriptor()
	// device.DefaultVendor holds the default value on creation for the vendor field.
	device.DefaultVendor = deviceDescVendor.Default.(string)
	// deviceDescModel is the schema descriptor for model field.
	deviceDescModel := deviceFields[4].Descriptor()
	// device.DefaultModel holds the default value on creation for the model field.
	device.DefaultModel = deviceDescModel.Default.(string)
	// deviceDescLocation is the schema descriptor for location field.
	deviceDescLocation := deviceFields[5].Descriptor()
	// device.DefaultLocation holds the default value on creation for the location field.
	device.DefaultLocation = deviceDescLocation.Default.(string)
	// deviceDescSn is the schema descriptor for sn field.
	deviceDescSn := deviceFields[6].Descriptor()
	// device.DefaultSn holds the default value on creation for the sn field.
	device.DefaultSn = deviceDescSn.Default.(string)
	// deviceDescServer is the schema descriptor for server field.
	deviceDescServer := deviceFields[7].Descriptor()
	// device.DefaultServer holds the default value on creation for the server field.
	device.DefaultServer = deviceDescServer.Default.(string)
	// deviceDescDriver is the schema descriptor for driver field.
	deviceDescDriver := deviceFields[8].Descriptor()
	// device.DefaultDriver holds the default value on creation for the driver field.
	device.DefaultDriver = deviceDescDriver.Default.(string)
	// deviceDescTags is the schema descriptor for tags field.
	deviceDescTags := deviceFields[9].Descriptor()
	// device.DefaultTags holds the default value on creation for the tags field.
	device.DefaultTags = deviceDescTags.Default.([]string)
	// deviceDescSSHUser is the schema descriptor for ssh_user field.
	deviceDescSSHUser := deviceFields[10].Descriptor()
	// device.DefaultSSHUser holds the default value on creation for the ssh_user field.
	device.DefaultSSHUser = deviceDescSSHUser.Default.(string)
	// deviceDescSSHPass is the schema descriptor for ssh_pass field.
	deviceDescSSHPass := deviceFields[11].Descriptor()
	// device.DefaultSSHPass holds the default value on creation for the ssh_pass field.
	device.DefaultSSHPass = deviceDescSSHPass.Default.(string)
	// deviceDescGpu is the schema descriptor for gpu field.
	deviceDescGpu := deviceFields[14].Descriptor()
	// device.DefaultGpu holds the default value on creation for the gpu field.
	device.DefaultGpu = deviceDescGpu.Default.(bool)
	// deviceDescCreatedAt is the schema descriptor for created_at field.
	deviceDescCreatedAt := deviceFields[15].Descriptor()
	// device.DefaultCreatedAt holds the default value on creation for the created_at field.
	device.DefaultCreatedAt = deviceDescCreatedAt.Default.(func() time.Time)
	// deviceDescUpdatedAt is the schema descriptor for updated_at field.
	deviceDescUpdatedAt := deviceFields[16].Descriptor()
	// device.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	device.DefaultUpdatedAt = deviceDescUpdatedAt.Default.(func() time.Time)
	// device.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	device.UpdateDefaultUpdatedAt = deviceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// deviceDescID is the schema descriptor for id field.
	deviceDescID := deviceFields[0].Descriptor()
	// device.IDValidator is a validator for the "id" field. It is called by the builders before save.
	device.IDValidator = deviceDescID.Validators[0].(func(int) error)
	topologylinkFields := schema.TopologyLink{}.Fields()
	_ = topologylinkFields
	// topologylinkDescSourceIP is the schema descriptor for source_ip field.
	topologylinkDescSourceIP := topologylinkFields[1].Descriptor()
	// topologylink.SourceIPValidator is a validator for the "source_ip" field. It is called by the builders before save.
	topologylink.SourceIPValidator = topologylinkDescSourceIP.Validators[0].(func(string) error)
	// topologylinkDescTargetIP is the schema descriptor for target_ip field.
	topologylinkDescTargetIP := topologylinkFields[2].Descriptor()
	// topologylink.TargetIPValidator is a validator for the "target_ip" field. It is called by the builders before save.
	topologylink.TargetIPValidator = topologylinkDescTargetIP.Validators[0].(func(string) error)
	// topologylinkDescLinkType is the schema descriptor for link_type field.
	topologylinkDescLinkType := topologylinkFields[3].Descriptor()
	// topologylink.DefaultLinkType holds the default value on creation for the link_type field.
	topologylink.DefaultLinkType = topologylinkDescLinkType.Default.(string)
	// topologylinkDescLabel is the schema descriptor for label field.
	topologylinkDescLabel := topologylinkFields[4].Descriptor()
	// topologylink.DefaultLabel holds the default value on creation for the label field.
	topologylink.DefaultLabel = topologylinkDescLabel.Default.(string)
	// topologylinkDescCreatedAt is the schema descriptor for created_at field.
	topologylinkDescCreatedAt := topologylinkFields[5].Descriptor()
	// topologylink.DefaultCreatedAt holds the default value on creation for the created_at field.
	topologylink.DefaultCreatedAt = topologylinkDescCreatedAt.Default.(func() time.Time)
	// topologylinkDescID is the schema descriptor for id field.
	topologylinkDescID := topologylinkFields[0].Descriptor()
	// topologylink.IDValidator is a validator for the "id" field. It is called by the builders before save.
	topologylink.IDValidator = topologylinkDescID.Validators[0].(func(int) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescActive is the schema descriptor for active field.
	userDescActive := userFields[4].Descriptor()
	// user.DefaultActive holds the default value on creation for the active field.
	user.DefaultActive = userDescActive.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(int) error)
}
