// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/netops/asset-manager/ent/predicate"
	"github.com/netops/asset-manager/ent/topologylink"
)

// TopologyLinkDelete is the builder for deleting a TopologyLink entity.
type TopologyLinkDelete struct {
	config
	hooks    []Hook
	mutation *TopologyLinkMutation
}

// Where appends a list predicates to the TopologyLinkDelete builder.
func (_d *TopologyLinkDelete) Where(ps ...predicate.TopologyLink) *TopologyLinkDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TopologyLinkDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TopologyLinkDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TopologyLinkDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(topologylink.Table, sqlgraph.NewFieldSpec(topologylink.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TopologyLinkDeleteOne is the builder for deleting a single TopologyLink entity.
type TopologyLinkDeleteOne struct {
	_d *TopologyLinkDelete
}

// Where appends a list predicates to the TopologyLinkDelete builder.
func (_d *TopologyLinkDeleteOne) Where(ps ...predicate.TopologyLink) *TopologyLinkDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TopologyLinkDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{topologylink.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TopologyLinkDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
