// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/netops/asset-manager/ent/topologylink"
)

// TopologyLinkCreate is the builder for creating a TopologyLink entity.
type TopologyLinkCreate struct {
	config
	mutation *TopologyLinkMutation
	hooks    []Hook
}

// SetSourceIP sets the "source_ip" field.
func (_c *TopologyLinkCreate) SetSourceIP(v string) *TopologyLinkCreate {
	_c.mutation.SetSourceIP(v)
	return _c
}

// SetTargetIP sets the "target_ip" field.
func (_c *TopologyLinkCreate) SetTargetIP(v string) *TopologyLinkCreate {
	_c.mutation.SetTargetIP(v)
	return _c
}

// SetLinkType sets the "link_type" field.
func (_c *TopologyLinkCreate) SetLinkType(v string) *TopologyLinkCreate {
	_c.mutation.SetLinkType(v)
	return _c
}

// SetNillableLinkType sets the "link_type" field if the given value is not nil.
func (_c *TopologyLinkCreate) SetNillableLinkType(v *string) *TopologyLinkCreate {
	if v != nil {
		_c.SetLinkType(*v)
	}
	return _c
}

// SetLabel sets the "label" field.
func (_c *TopologyLinkCreate) SetLabel(v string) *TopologyLinkCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_c *TopologyLinkCreate) SetNillableLabel(v *string) *TopologyLinkCreate {
	if v != nil {
		_c.SetLabel(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TopologyLinkCreate) SetCreatedAt(v time.Time) *TopologyLinkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TopologyLinkCreate) SetNillableCreatedAt(v *time.Time) *TopologyLinkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TopologyLinkCreate) SetID(v int) *TopologyLinkCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TopologyLinkMutation object of the builder.
func (_c *TopologyLinkCreate) Mutation() *TopologyLinkMutation {
	return _c.mutation
}

// Save creates the TopologyLink in the database.
func (_c *TopologyLinkCreate) Save(ctx context.Context) (*TopologyLink, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TopologyLinkCreate) SaveX(ctx context.Context) *TopologyLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TopologyLinkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TopologyLinkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TopologyLinkCreate) defaults() {
	if _, ok := _c.mutation.LinkType(); !ok {
		v := topologylink.DefaultLinkType
		_c.mutation.SetLinkType(v)
	}
	if _, ok := _c.mutation.Label(); !ok {
		v := topologylink.DefaultLabel
		_c.mutation.SetLabel(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := topologylink.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TopologyLinkCreate) check() error {
	if _, ok := _c.mutation.SourceIP(); !ok {
		return &ValidationError{Name: "source_ip", err: errors.New(`ent: missing required field "TopologyLink.source_ip"`)}
	}
	if v, ok := _c.mutation.SourceIP(); ok {
		if err := topologylink.SourceIPValidator(v); err != nil {
			return &ValidationError{Name: "source_ip", err: fmt.Errorf(`ent: validator failed for field "TopologyLink.source_ip": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetIP(); !ok {
		return &ValidationError{Name: "target_ip", err: errors.New(`ent: missing required field "TopologyLink.target_ip"`)}
	}
	if v, ok := _c.mutation.TargetIP(); ok {
		if err := topologylink.TargetIPValidator(v); err != nil {
			return &ValidationError{Name: "target_ip", err: fmt.Errorf(`ent: validator failed for field "TopologyLink.target_ip": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LinkType(); !ok {
		return &ValidationError{Name: "link_type", err: errors.New(`ent: missing required field "TopologyLink.link_type"`)}
	}
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "TopologyLink.label"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TopologyLink.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := topologylink.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "TopologyLink.id": %w`, err)}
		}
	}
	return nil
}

func (_c *TopologyLinkCreate) sqlSave(ctx context.Context) (*TopologyLink, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TopologyLinkCreate) createSpec() (*TopologyLink, *sqlgraph.CreateSpec) {
	var (
		_node = &TopologyLink{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(topologylink.Table, sqlgraph.NewFieldSpec(topologylink.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.SourceIP(); ok {
		_spec.SetField(topologylink.FieldSourceIP, field.TypeString, value)
		_node.SourceIP = value
	}
	if value, ok := _c.mutation.TargetIP(); ok {
		_spec.SetField(topologylink.FieldTargetIP, field.TypeString, value)
		_node.TargetIP = value
	}
	if value, ok := _c.mutation.LinkType(); ok {
		_spec.SetField(topologylink.FieldLinkType, field.TypeString, value)
		_node.LinkType = value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(topologylink.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(topologylink.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// TopologyLinkCreateBulk is the builder for creating many TopologyLink entities in bulk.
type TopologyLinkCreateBulk struct {
	config
	err      error
	builders []*TopologyLinkCreate
}

// Save creates the TopologyLink entities in the database.
func (_c *TopologyLinkCreateBulk) Save(ctx context.Context) ([]*TopologyLink, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TopologyLink, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TopologyLinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TopologyLinkCreateBulk) SaveX(ctx context.Context) []*TopologyLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TopologyLinkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TopologyLinkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
