// Code generated by ent, DO NOT EDIT.

package topologylink

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the topologylink type in the database.
	Label = "topology_link"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSourceIP holds the string denoting the source_ip field in the database.
	FieldSourceIP = "source_ip"
	// FieldTargetIP holds the string denoting the target_ip field in the database.
	FieldTargetIP = "target_ip"
	// FieldLinkType holds the string denoting the link_type field in the database.
	FieldLinkType = "link_type"
	// FieldLabel holds the string denoting the label field in the database.
	FieldLabel = "label"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the topologylink in the database.
	Table = "topology_links"
)

// Columns holds all SQL columns for topologylink fields.
var Columns = []string{
	FieldID,
	FieldSourceIP,
	FieldTargetIP,
	FieldLinkType,
	FieldLabel,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SourceIPValidator is a validator for the "source_ip" field. It is called by the builders before save.
	SourceIPValidator func(string) error
	// TargetIPValidator is a validator for the "target_ip" field. It is called by the builders before save.
	TargetIPValidator func(string) error
	// DefaultLinkType holds the default value on creation for the "link_type" field.
	DefaultLinkType string
	// DefaultLabel holds the default value on creation for the "label" field.
	DefaultLabel string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the TopologyLink queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySourceIP orders the results by the source_ip field.
func BySourceIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceIP, opts...).ToFunc()
}

// ByTargetIP orders the results by the target_ip field.
func ByTargetIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetIP, opts...).ToFunc()
}

// ByLinkType orders the results by the link_type field.
func ByLinkType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLinkType, opts...).ToFunc()
}

// ByLabel orders the results by the label field.
func ByLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLabel, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
