// Code generated by ent, DO NOT EDIT.

package topologylink

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/netops/asset-manager/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldLTE(FieldID, id))
}

// SourceIP applies equality check predicate on the "source_ip" field. It's identical to SourceIPEQ.
func SourceIP(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldEQ(FieldSourceIP, v))
}

// TargetIP applies equality check predicate on the "target_ip" field. It's identical to TargetIPEQ.
func TargetIP(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldEQ(FieldTargetIP, v))
}

// LinkType applies equality check predicate on the "link_type" field. It's identical to LinkTypeEQ.
func LinkType(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldEQ(FieldLinkType, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldEQ(FieldCreatedAt, v))
}

// SourceIPEQ applies the EQ predicate on the "source_ip" field.
func SourceIPEQ(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldEQ(FieldSourceIP, v))
}

// SourceIPNEQ applies the NEQ predicate on the "source_ip" field.
func SourceIPNEQ(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldNEQ(FieldSourceIP, v))
}

// SourceIPIn applies the In predicate on the "source_ip" field.
func SourceIPIn(vs ...string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldIn(FieldSourceIP, vs...))
}

// SourceIPNotIn applies the NotIn predicate on the "source_ip" field.
func SourceIPNotIn(vs ...string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldNotIn(FieldSourceIP, vs...))
}

// SourceIPGT applies the GT predicate on the "source_ip" field.
func SourceIPGT(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldGT(FieldSourceIP, v))
}

// SourceIPGTE applies the GTE predicate on the "source_ip" field.
func SourceIPGTE(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldGTE(FieldSourceIP, v))
}

// SourceIPLT applies the LT predicate on the "source_ip" field.
func SourceIPLT(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldLT(FieldSourceIP, v))
}

// SourceIPLTE applies the LTE predicate on the "source_ip" field.
func SourceIPLTE(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldLTE(FieldSourceIP, v))
}

// SourceIPContains applies the Contains predicate on the "source_ip" field.
func SourceIPContains(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldContains(FieldSourceIP, v))
}

// SourceIPHasPrefix applies the HasPrefix predicate on the "source_ip" field.
func SourceIPHasPrefix(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldHasPrefix(FieldSourceIP, v))
}

// SourceIPHasSuffix applies the HasSuffix predicate on the "source_ip" field.
func SourceIPHasSuffix(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldHasSuffix(FieldSourceIP, v))
}

// SourceIPEqualFold applies the EqualFold predicate on the "source_ip" field.
func SourceIPEqualFold(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldEqualFold(FieldSourceIP, v))
}

// SourceIPContainsFold applies the ContainsFold predicate on the "source_ip" field.
func SourceIPContainsFold(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldContainsFold(FieldSourceIP, v))
}

// TargetIPEQ applies the EQ predicate on the "target_ip" field.
func TargetIPEQ(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldEQ(FieldTargetIP, v))
}

// TargetIPNEQ applies the NEQ predicate on the "target_ip" field.
func TargetIPNEQ(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldNEQ(FieldTargetIP, v))
}

// TargetIPIn applies the In predicate on the "target_ip" field.
func TargetIPIn(vs ...string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldIn(FieldTargetIP, vs...))
}

// TargetIPNotIn applies the NotIn predicate on the "target_ip" field.
func TargetIPNotIn(vs ...string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldNotIn(FieldTargetIP, vs...))
}

// TargetIPGT applies the GT predicate on the "target_ip" field.
func TargetIPGT(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldGT(FieldTargetIP, v))
}

// TargetIPGTE applies the GTE predicate on the "target_ip" field.
func TargetIPGTE(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldGTE(FieldTargetIP, v))
}

// TargetIPLT applies the LT predicate on the "target_ip" field.
func TargetIPLT(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldLT(FieldTargetIP, v))
}

// TargetIPLTE applies the LTE predicate on the "target_ip" field.
func TargetIPLTE(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldLTE(FieldTargetIP, v))
}

// TargetIPContains applies the Contains predicate on the "target_ip" field.
func TargetIPContains(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldContains(FieldTargetIP, v))
}

// TargetIPHasPrefix applies the HasPrefix predicate on the "target_ip" field.
func TargetIPHasPrefix(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldHasPrefix(FieldTargetIP, v))
}

// TargetIPHasSuffix applies the HasSuffix predicate on the "target_ip" field.
func TargetIPHasSuffix(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldHasSuffix(FieldTargetIP, v))
}

// TargetIPEqualFold applies the EqualFold predicate on the "target_ip" field.
func TargetIPEqualFold(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldEqualFold(FieldTargetIP, v))
}

// TargetIPContainsFold applies the ContainsFold predicate on the "target_ip" field.
func TargetIPContainsFold(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldContainsFold(FieldTargetIP, v))
}

// LinkTypeEQ applies the EQ predicate on the "link_type" field.
func LinkTypeEQ(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldEQ(FieldLinkType, v))
}

// LinkTypeNEQ applies the NEQ predicate on the "link_type" field.
func LinkTypeNEQ(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldNEQ(FieldLinkType, v))
}

// LinkTypeIn applies the In predicate on the "link_type" field.
func LinkTypeIn(vs ...string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldIn(FieldLinkType, vs...))
}

// LinkTypeNotIn applies the NotIn predicate on the "link_type" field.
func LinkTypeNotIn(vs ...string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldNotIn(FieldLinkType, vs...))
}

// LinkTypeGT applies the GT predicate on the "link_type" field.
func LinkTypeGT(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldGT(FieldLinkType, v))
}

// LinkTypeGTE applies the GTE predicate on the "link_type" field.
func LinkTypeGTE(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldGTE(FieldLinkType, v))
}

// LinkTypeLT applies the LT predicate on the "link_type" field.
func LinkTypeLT(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldLT(FieldLinkType, v))
}

// LinkTypeLTE applies the LTE predicate on the "link_type" field.
func LinkTypeLTE(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldLTE(FieldLinkType, v))
}

// LinkTypeContains applies the Contains predicate on the "link_type" field.
func LinkTypeContains(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldContains(FieldLinkType, v))
}

// LinkTypeHasPrefix applies the HasPrefix predicate on the "link_type" field.
func LinkTypeHasPrefix(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldHasPrefix(FieldLinkType, v))
}

// LinkTypeHasSuffix applies the HasSuffix predicate on the "link_type" field.
func LinkTypeHasSuffix(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldHasSuffix(FieldLinkType, v))
}

// LinkTypeEqualFold applies the EqualFold predicate on the "link_type" field.
func LinkTypeEqualFold(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldEqualFold(FieldLinkType, v))
}

// LinkTypeContainsFold applies the ContainsFold predicate on the "link_type" field.
func LinkTypeContainsFold(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldContainsFold(FieldLinkType, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldContainsFold(FieldLabel, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TopologyLink {
	return predicate.TopologyLink(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TopologyLink) predicate.TopologyLink {
	return predicate.TopologyLink(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TopologyLink) predicate.TopologyLink {
	return predicate.TopologyLink(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TopologyLink) predicate.TopologyLink {
	return predicate.TopologyLink(sql.NotPredicates(p))
}
