// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Backup is the predicate function for backup builders.
type Backup func(*sql.Selector)

// Device is the predicate function for device builders.
type Device func(*sql.Selector)

// TopologyLink is the predicate function for topologylink builders.
type TopologyLink func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
